version: '3.4'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  redis_commander:
    image: rediscommander/redis-commander
    ports: 
      - 6378:6378
    depends_on:
      - redis
    environment:
      PORT: 6378
      REDIS_PORT: 6379
      REDIS_HOST: "redis"
  mongo:
    command: --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db